### ISSUE TITLE
Using the Await algorithm in the specification.

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1774]
There is such an operation in the ECMAScript specification called [Await](https://www.ecma-international.org/ecma-262/#await). If you go to this operation, you can find the following lines:

> Algorithm steps that say
> 
> > 1. Let completion be Await(value).
> 
> mean the same thing as:
> 
> > 1. Let asyncContext be the running execution context.
> > 2. Let promise be ? PromiseResolve(%Promise%, « value »).
> > 3. Let stepsFulfilled be the algorithm steps defined in Await Fulfilled Functions.
> > 4. Let onFulfilled be CreateBuiltinFunction(stepsFulfilled, « [[AsyncContext]] »).
> > 5. Set onFulfilled.[[AsyncContext]] to asyncContext.
> > 6. Let stepsRejected be the algorithm steps defined in Await Rejected Functions.
> > 7. Let onRejected be CreateBuiltinFunction(stepsRejected, « [[AsyncContext]] »).
> > 8. Set onRejected.[[AsyncContext]] to asyncContext.
> > 9. Perform ! PerformPromiseThen(promise, onFulfilled, onRejected).
> > 10. Remove asyncContext from the execution context stack and restore the execution context that is at the top of the execution context stack as the running execution context.
> > 11. Set the code evaluation state of asyncContext such that when evaluation is resumed with a Completion completion, the following steps of the algorithm that invoked Await will be performed, with completion available.
> > 12. Return.
> > 13. NOTE: This returns to the evaluation of the operation that had most previously resumed evaluation of asyncContext.

As can be understood from the cited, `Let completion be Await (value)` is a shorthand of the whole list of operations that are listed above. But if you look at the specification more carefully, you can find other combinations with calling the Await operation:
- Set value to ? Await (value).
- Return ? Await (value).
- Let awaited be Await (resumptionValue.[[Value]]).

What to do with these variants? Also replace as in the example c `Let ...` from Await?
For example, take the expression `await UnaryExpression`, it is represented by the following steps:

1. Let exprRef be the result of evaluating UnaryExpression.
2. Let value be ? GetValue(exprRef).
3. Return ? Await(value).

Therefore, the last step is completely replaced by the list of operations from Await. But the question arises - how do we return the result of the `await UnaryExpression` operation if we do not have a step with the Return statement in the list of Await operations?

That is, the main question is this: how to apply the entire list of operations for concrete shorthands.

**Comment by bakkot** [comment]
> What to do with these variants? 

These should generally be understood to mean

```
Let hygienicTemp be Await (value).
Set value to ? hygienicTemp.
```

or

```
Let hygienicTemp be Await (value).
Return ? hygienicTemp.
```
or similar (and then replacing the `Await` step with the long sequence of steps you mention).

The spec needs be updated to explicitly allow these forms (or to stop using them).

**Comment by devsnek** [comment]
Is there even any reason for `Await` to be a macro?

**Comment by dSalieri** [comment]
@bakkot interesting. For `Let completion be Await (value)`, the following should be:
```
Let hygienicTemp be Await (value).
Let value to ? hygienicTemp.
```
I am right?

Is replacing a shorthand with a sequence of steps partial or full? By full, I mean replacing the entire step. By partial, only the call `Await (value)`.

---

And yes, I also asked about `await UnaryExpression`. If we represent this expression through the rules that you showed, it should look something like this:

> 1. Let exprRef be the result of evaluating UnaryExpression.
> 2. Let value be ? GetValue(exprRef).
> > 1. Let asyncContext be the running execution context.
> > 2. Let promise be ? PromiseResolve(%Promise%, « value »).
> > 3. Let stepsFulfilled be the algorithm steps defined in Await Fulfilled Functions.
> > 4. Let onFulfilled be CreateBuiltinFunction(stepsFulfilled, « [[AsyncContext]] »).
> > 5. Set onFulfilled.[[AsyncContext]] to asyncContext.
> > 6. Let stepsRejected be the algorithm steps defined in Await Rejected Functions.
> > 7. Let onRejected be CreateBuiltinFunction(stepsRejected, « [[AsyncContext]] »).
> > 8. Set onRejected.[[AsyncContext]] to asyncContext.
> > 9. Perform ! PerformPromiseThen(promise, onFulfilled, onRejected).
> > 10. Remove asyncContext from the execution context stack and restore the execution context that is at the top of the execution context stack as the running execution context.
> > 11. Set the code evaluation state of asyncContext such that when evaluation is resumed with a Completion completion, the following steps of the algorithm that invoked Await will be performed, with completion available.
> > 12. Return.
> > 13. NOTE: This returns to the evaluation of the operation that had most previously resumed evaluation of asyncContext.
> 3. Return ? completion.

Did I understand you correctly?

**Comment by bakkot** [comment]
@devsnek It needs to be a macro since it contains a `Return`. (Two, actually, though the other is behind the `?` macro.)

---

@dSalier

> I am right?

I'm not sure what you're asking. The spec currently says how to interpret `Let completion be Await (value)`. What I was intending to answer is how to interpret `Set value to ? Await (value).` and `Return ? Await (value).` respectively.

> Is replacing a shorthand with a sequence of steps partial or full? By full, I mean replacing the entire step.

Full. But currently it only tells you how to replace a step which looks like `Let completion be Await(value)`. It should be expanded to tell you how to replace other full steps. 

> Did I understand you correctly?

Yes, I think that interpretation is correct.

**Comment by dSalieri** [comment]
@bakkot alright, I understand you. As for the variants that you explained is clear. But the record presented by the specification is not entirely clear `Let completion be Await (value)` if it is completely replaced by Await steps. It’s not entirely clear what the result of the Await execution will be, because result of execution Await is not saved anywhere. Therefore, I suggested that her record should be like those that you cited as an example:

```
/// For Set hygienicTemp be Await (value)

Let hygienicTemp be Await (value).
Set value to ? hygienicTemp.
```
as
```
/// For Let completion be Await (value)

Let completion be Await (value).
Let value to ? completion.

```
Isn't that correct?

**Comment by bakkot** [comment]
> It’s not entirely clear what the result of the Await execution will be, because result of execution Await is not saved anywhere.

Step 11 of the Await macro says

> Set the code evaluation state of asyncContext such that when evaluation is resumed with a Completion completion, the following steps of the algorithm that invoked Await will be performed, **with completion available**.

which is how the result is saved. (Emphasis added.)

The point of the examples I gave was to explain how to rewrite other uses of `Await` so that they contained a step which looked like "Let completion be Await (value).". The spec already says how to interpret such steps, namely, to replace them entirely with the algorithm steps from the Await macro.

If you start out with a step which looks like "Let completion be Await (value).", the examples I provided are not relevant.

**Comment by dSalieri** [comment]
@bakkot hmm, yes. If you imagine that step 11 of Await declares variable with completion, which is subsequently used by different algorithms, then everything is fine.

>If you start out with a step which looks like "Let completion be Await (value).", the examples I provided are not relevant.

I do not understand what you are talking about, I'm sorry.

**Comment by bakkot** [comment]
> If you imagine that step 11 of Await declares variable with completion, which is subsequently used by different algorithms, then everything is fine.

Yes, that is the intent.

**Comment by dSalieri** [comment]
@bakkot
> Yes, that is the intent.

alright.

Besides, can you explain what I asked you above?

**Comment by bakkot** [comment]
I don't understand your other questions, I'm afraid.

**Comment by dSalieri** [comment]
@bakkot awkwardly situation. I meant that I did not understand your paragraph.
>If you start out with a step which looks like "Let completion be Await (value).", the examples I provided are not relevant.

I did not understand what was said in it. What are we talking about here? Explain, please.

**Comment by bakkot** [comment]
That was in reply to your comment about

> It’s not entirely clear what the result of the Await execution will be, because result of execution Await is not saved anywhere. Therefore, I suggested that her record should be like those that you cited as an example:

I was responding that the examples I was giving were explaining how to translate other formats into the `Let completion be Await (value)` format, and are not relevant to understanding `Let completion be Await (value)` itself.

**Comment by dSalieri** [comment]
@bakkot  I seem to understand you. The notation `Let completion be Await (value)` is self-sufficient and does not need those additional transformations that you showed above for other cases. Right?

**Comment by bakkot** [comment]
Right.

**Comment by dSalieri** [comment]
@bakkot well, thanks for your explanations. Have a nice day.

**Comment by ljharb** [comment]
Sounds like this is resolved.

**Comment by bakkot** [comment]
@ljharb There is still an issue, which is that the spec uses `Await` in a variety of ways, like `Return ? Await (value).`, which it does not tell you how to interpret. It only specifies how to interpret `Let completion be Await(value).`

**Comment by ljharb** [comment]
Ok, reopening pending that fix.

**Comment by bakkot** [comment]
This was fixed by https://github.com/tc39/ecma262/pull/2959.
